name: CI/CD for project

on:
  push:
    branches:
      - development
      - test
      - main
  pull_request:
    branches:
      - development
      - test
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node modules
        run: yarn
      - name: Build static files
        run: yarn build:dev
      - name: Unit tests
        run: yarn test:unit
      - name: E2E tests
        run: yarn test:e2e
