name: CI/CD for development branch

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node modules
        run: yarn
      - name: Build static files
        run: yarn build:dev

  tests:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
      - name: Unit tests
        run: yarn vitest run --passWithNoTests
      - name: E2E tests
        run: yarn test:e2e

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ success() }}
    steps:
      - name: Unit tests
        run: yarn vitest run --passWithNoTests
      - name: E2E tests
        run: yarn test:e2e
